version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: pizzadao-postgres
    environment:
      POSTGRES_USER: pizzadao
      POSTGRES_PASSWORD: pizzadao
      POSTGRES_DB: pizzadao
    ports:
      - '3009:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
